# /etc/postfix/Makefile
#  __  __       _         __ _ _
# |  \/  | __ _| | _____ / _(_) | ___
# | |\/| |/ _` | |/ / _ \ |_| | |/ _ \
# | |  | | (_| |   <  __/  _| | |  __/
# |_|  |_|\__,_|_|\_\___|_| |_|_|\___|
# -------------------------------------------------------------------------------------------------
MAILOWNER  = postfix
MAILGROUP  = postfix
CONFIGROOT = {{ postfix.configroot }}
CERTANDKEY = {{ postfix.tlscertdir }}
POSTFIX    = {{ postfix.serverroot }}/sbin/postfix
POSTMAP    = {{ postfix.serverroot }}/sbin/postmap
POSTCONF   = {{ postfix.serverroot }}/sbin/postconf
POSTALIAS  = {{ postfix.serverroot }}/sbin/postalias
POSTQUEUE  = {{ postfix.serverroot }}/sbin/postqueue
POSTSUPER  = {{ postfix.serverroot }}/sbin/postsuper
QUEUEDIR   = {{ postfix.mailqueues }}
EXPIRES    = 14

NEWALIASES = /usr/bin/newaliases
MKDIR      = mkdir -p
CHMOD      = chmod -c
CHOWN      = chown -c
RM         = rm -f
MV         = mv
CP         = cp -p
UPDATE     = cp -up

POSTFIXCTL = check reload
SYSTEMDCTL = start stop restart

MYHOSTNAME = $(shell $(POSTCONF) -h myhostname)
MYDOMAIN   = $(shell $(POSTCONF) -h mydomain)
MAPFILES   = $(shell $(POSTCONF) | tr ',' '\n' | grep -E '(hash|cidr|pcre):{{ postfix.configroot }}' | sed 's/^.*://g' | sort -u)
HELDQUEUES = $(shell find $(QUEUEDIR)/hold -type f -ctime +$(EXPIRES))
POSTMASTER = postmaster

.DEFAULT_GOAL = status

# -------------------------------------------------------------------------------------------------
.PHONY: clean
all:
	@$(foreach v, $(MAPFILES), test -f `basename $v` && $(MAKE) --no-print-directory `basename $v`.db;)
	$(MAKE) sni-certificates
	@echo

aliases.db: aliases
	test -f $< && $(NEWALIASES)

%.db: %.in
	test -f $<
	$(POSTMAP) $< && $(MV) $<.db $@ && $(RM) $<

%.in: %
	test -f $< && $(CP) $< $<.in

serversni.db: serversni
	$(MAKE) sni-certificates
	test -f $< && $(POSTMAP) -F hash:$<
	test -f $@ && $(CHOWN) root.$(MAILGROUP) $@

smtpauth.db: smtpauth
	test -f $< && $(POSTMAP) $<
	test -f $@ && $(CHOWN) root.$(MAILGROUP) $@

sni-certificates:
	cd ./tls && $(MAKE) $@

# -------------------------------------------------------------------------------------------------
$(POSTFIXCTL):
	$(POSTFIX) $@

$(SYSTEMDCTL): check
	/usr/bin/systemctl $@ postfix

status:
	/usr/bin/systemctl $@ postfix

# -------------------------------------------------------------------------------------------------
auth-plain-password:
	@test -n "$(U)" || (echo 'Specify "U" macro like: make U=sasl-user@example.jp' && false)
	@test -n "$(P)" || (echo 'Specify "P" macro like: make P=sasl-user-password'   && false)
	@printf "%s\0%s\0%s" $(U) $(U) $(P) | openssl base64 -e | tr -d '\n'; echo

new-cert-by-dns:
	certbot certonly --manual --preferred-challenges dns -d $(MYHOSTNAME) -m $(POSTMASTER)@$(MYDOMAIN) --agree-tos

new-cert-by-web:
	certbot certonly --standalone -d $(MYHOSTNAME) -m $(POSTMASTER)@$(MYDOMAIN) --agree-tos

# -------------------------------------------------------------------------------------------------
remove-held-queues:
	@$(foreach v, $(HELDQUEUES), $(POSTSUPER) -d `basename $v`;)

clean:
	$(RM) *.in *.db.db
	$(MKDIR) $(CONFIGROOT)/histories
	$(MV) ./*~ ./histories/ 2> /dev/null || true

