---
#                  _    __ _       __      _       __     ___            _        
#  _ __   ___  ___| |_ / _(_)_  __/ /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
# | '_ \ / _ \/ __| __| |_| \ \/ / || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | |_) | (_) \__ \ |_|  _| |>  <| || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
# | .__/ \___/|___/\__|_| |_/_/\_\ || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
# |_|                             \_\_|        |___/_/                            
# check-virus
- block:
    - name: check-virus | RedHat | ClamSMTP should be installed
      yum:
        name:  "{{ item }}"
        state: "present"
      with_items:
        - "clamsmtp"

    - name: check-virus | RedHat | Each user should be included in virusgroup
      user:
        name:   "{{ item }}"
        groups: "virusgroup"
        state:  "present"
      with_items:
        - "clamsmtp"

    - name: check-virus | RedHat | Runtime directory should be created
      file:
        path:  "{{ postfix.checkvirus.runtime }}"
        mode:  "0755"
        owner: "clamsmtp"
        group: "mail"
        state: "directory"

    - name: check-virus | RedHat | Temporary directory should be created
      file:
        path:  "{{ postfix.checkvirus.tempdir }}"
        mode:  "0755"
        owner: "clamsmtp"
        group: "mail"
        state: "directory"

    - name: check-virus | RedHat | Configuration files should be deployed
      notify: Restart clamsmtpd
      template:
        src:  "etc/clamsmtpd.conf.j2"
        dest: "/etc/clamsmtpd.conf"
        mode: "0644"

    - name: check-virus | RedHat | Unit file should be deployed
      notify: Restart clamsmtpd
      template:
        src:  "usr/lib/systemd/system/clamsmtpd.service.j2"
        dest: "/usr/lib/systemd/system/clamsmtpd.service"
        mode: "0644"

  when: ansible_os_family == "RedHat"

