---
#                  _    __ _       __      _       __     ___            _        
#  _ __   ___  ___| |_ / _(_)_  __/ /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
# | '_ \ / _ \/ __| __| |_| \ \/ / || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | |_) | (_) \__ \ |_|  _| |>  <| || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
# | .__/ \___/|___/\__|_| |_/_/\_\ || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
# |_|                             \_\_|        |___/_/                            
# create-user
- name: create-user | Group for virtual mailbox should be created
  group:
    name:  "{{ postfix.mailconfig.mailbox.group }}"
    gid:   "{{ postfix.mailconfig.mailbox.gid }}"
    state: "present"

- name: create-user | User for virtual mailbox should be created
  user:
    createhome: "yes"
    comment:    "{{ postfix.mailconfig.mailbox.comment }}"
    password:   "{{ postfix.mailconfig.mailbox.password }}"
    name:  "{{ postfix.mailconfig.mailbox.username }}"
    uid:   "{{ postfix.mailconfig.mailbox.uid }}"
    group: "{{ postfix.mailconfig.mailbox.group }}"
    shell: "{{ postfix.mailconfig.mailbox.shell }}"
    home:  "{{ postfix.mailconfig.mailbox.home }}"
    state: "present"

- name: create-user | Sub directories should be created at the virtmail home
  file:
    path:  "{{ item }}"
    owner: "{{ postfix.mailconfig.mailbox.username }}"
    group: "{{ postfix.mailconfig.mailbox.group }}"
    mode:  "0770"
    state: "directory"
  with_items:
    - "{{ postfix.mailconfig.mailbox.root }}"
    - "{{ postfix.mailconfig.mailbox.conf }}"
    - "{{ postfix.mailconfig.mailbox.logs }}"
    - "{{ postfix.mailconfig.mailbox.sbin }}"

