---
#                  _    __ _       __      _       __     ___            _        
#  _ __   ___  ___| |_ / _(_)_  __/ /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
# | '_ \ / _ \/ __| __| |_| \ \/ / || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | |_) | (_) \__ \ |_|  _| |>  <| || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
# | .__/ \___/|___/\__|_| |_/_/\_\ || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
# |_|                             \_\_|        |___/_/                            
# dkim-milter
- name: dkim-milter | Group for OpenDKIM should be created
  group:
    name:  "opendkim"
    state: "present"

- name: dkim-milter | opendkim user should be created
  user:
    createhome: "yes"
    comment:    "OpenDKIM Milter"
    password:   null
    name:       "opendkim"
    group:      "opendkim"
    groups:     "mail"
    shell:      "/sbin/nologin"
    home:       "{{ postfix.dkimmilter.runtime }}"
    state:      "present"

- name: dkim-milter | runtime directory should be 755
  file:
    path:  "{{ postfix.dkimmilter.runtime }}"
    mode:  "0755"
    owner: "opendkim"
    group: "opendkim"
    state: "directory"

- name: dkim-milter | /etc/dkim directory should be created
  file:
    path:  "{{ postfix.dkimmilter.confdir }}"
    mode:  "0755"
    owner: "root"
    group: "opendkim"
    state: "directory"

- name: dkim-milter | Sub directories in /etc/dkim should be created
  file:
    path:  "{{ postfix.dkimmilter.confdir }}/{{ item }}"
    mode:  "0750"
    owner: "opendkim"
    group: "opendkim"
    state: "directory"
  loop:
    - "keys"

- name: dkim-milter | /etc/opendkim.conf should be deployed
  notify: Restart OpenDKIM
  template:
    src:   "etc/opendkim.conf.j2"
    dest:  "/etc/opendkim.conf"
    mode:  "0644"
    owner: "root"
    group: "root"

- name: dkim-milter | RedHat | /etc/sysconfig/opendkim should be deployed
  when: ansible_os_family == "RedHat"
  notify: Restart OpenDKIM
  template:
    src:   "etc/sysconfig/opendkim.j2"
    dest:  "/etc/sysconfig/opendkim"
    mode:  "0644"
    owner: "root"
    group: "root"

- name: dkim-milter | Debian | /etc/default/opendkim should be deployed
  when: ansible_os_family == "Debina"
  notify: Restart OpenDKIM
  template:
    src:   "etc/default/opendkim.j2"
    dest:  "/etc/default/opendkim"
    mode:  "0644"
    owner: "root"
    group: "root"

- name: dkim-milter | tables for OpenDKIM should be deployed
  notify: Restart OpenDKIM
  template:
    src:   "etc/dkim/{{ item }}.j2"
    dest:  "{{ postfix.dkimmilter.confdir }}/{{ item }}"
    mode:  "0640"
    owner: "opendkim"
    group: "opendkim"
  loop:
    - "dkim-keytable"
    - "signing-table"
    - "trusted-hosts"
    - "ignored-hosts"

- name: dkim-milter | Each keys for OpenDKIM should be deployed
  notify: Restart OpenDKIM
  copy:
    src:   "{{ item }}"
    dest:  "{{ postfix.dkimmilter.confdir }}/keys/{{ item | basename }}"
    mode:  "0600"
    owner: "opendkim"
    group: "opendkim"
  with_fileglob: "files/etc/dkim/keys/*"

- name: dkim-milter | Generate a private key for the default selector
  shell: >
    test -f ./default.key || openssl genrsa 2048 > ./default.key
  args:
    chdir:   "{{ postfix.dkimmilter.confdir }}/keys"
    creates: "default.key"

- name: dkim-milter | Generate a public key for the default selector
  shell: >
    test -f ./default.pub || openssl rsa -in ./default.key -pubout > ./default.pub
  args:
    chdir:   "{{ postfix.dkimmilter.confdir }}/keys"
    creates: "default.pub"

- name: dkim-milter | Default keys should be owned by opendkim user
  file:
    path:  "{{ postfix.dkimmilter.confdir }}/keys/{{ item }}"
    mode:  "0600"
    owner: "opendkim"
    group: "opendkim"
  loop:
    - "default.key"
    - "default.pub"

- name: dkim-milter | Unit file should be deployed
  register: opendkim_unit_deployed
  notify: Restart OpenDKIM
  template:
    src:  "usr/lib/systemd/system/{{ postfix.dkimmilter.service }}.service.j2"
    dest: "/usr/lib/systemd/system/{{ postfix.dkimmilter.service }}.service"
    mode: "0644"

- name: dkim-milter | Reload systemd
  when: opendkim_unit_deployed.changed
  systemd:
    daemon_reload: "yes"
    name:  "{{ postfix.dkimmilter.service }}"
    state: "restarted"

- name: dkim-milter | OpenDKIM should be started
  when: postfix.dkimmilter.started == true
  service:
    name:  "{{ postfix.dkimmilter.service }}"
    state: "started"

- name: dkim-milter | OpenDKIM should be enabled
  when: postfix.dkimmilter.enabled == true
  service:
    name:    "{{ postfix.dkimmilter.service }}"
    enabled: "yes"

