---
#                  _    __ _       __      _       __     ___            _        
#  _ __   ___  ___| |_ / _(_)_  __/ /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
# | '_ \ / _ \/ __| __| |_| \ \/ / || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | |_) | (_) \__ \ |_|  _| |>  <| || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
# | .__/ \___/|___/\__|_| |_/_/\_\ || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
# |_|                             \_\_|        |___/_/                            
# install-pkg
- block:
    - name: install-pkg | RedHat | Postfix should be installed
      yum:
        name:  "postfix"
        state: "present"

    - name: install-pkg | RedHat | Postfix related packages should be installed
      yum:
        name:  "{{ item }}"
        state: "present"
      with_items:
        - "postfix-perl-scripts"
        - "postfix-sysvinit"
        - "postgrey"
        - "pypolicyd-spf"
        - "smtpping"
        - "sqlgrey"
        - "swaks"

    - name: install-pkg | RedHat | SASL related packages should be installed
      yum:
        name:  "{{ item }}"
        state: "present"
      with_items:
        - "cyrus-sasl"
        - "cyrus-sasl-devel"
        - "cyrus-sasl-lib"
        - "cyrus-sasl-md5"
        - "cyrus-sasl-ntlm"
        - "cyrus-sasl-plain"
        - "openssl"
        - "openssl-devel"
        - "openssl-libs"
        - "certbot"

    - name: install-pkg | RedHat | Email related packages should be installed
      yum:
        name:  "{{ item }}"
        state: "present"
      with_items:
        - "mailx"
        - "procmail"
  when: ansible_os_family == "RedHat"

