---
#                  _    __ _       __      _       __     ___            _        
#  _ __   ___  ___| |_ / _(_)_  __/ /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
# | '_ \ / _ \/ __| __| |_| \ \/ / || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | |_) | (_) \__ \ |_|  _| |>  <| || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
# | .__/ \___/|___/\__|_| |_/_/\_\ || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
# |_|                             \_\_|        |___/_/                            
# tasks file for ar-postfix-pkg
- include: install-pkg.yml
- include: create-user.yml
- include: dkim-milter.yml
  when: postfix.dkimmilter.enabled == true
- include: check-virus.yml
  when: postfix.checkvirus.enabled == true
- include: spam-filter.yml
  when: postfix.spamfilter.enabled == true
- include: make-config.yml
- include: setup-table.yml
  when: postfix.backend.enabled == true
- include: postfix-adm.yml
  when: postfix.postfixadmin.enabled == true
- include: check-dmarc.yml
  when: postfix.opendmarc.enabled == true
- include: rewrite-esa.yml
  when: postfix.rewriteesa.enabled == true
- include: mailman-pkg.yml
  when: mailman.enabled == true

- name: main | postfix should be included in other groups
  user:
    name:   "postfix"
    groups: "{{ postfix.mailconfig.alsobelong }}"
    state:  "present"

- include: build-local.yml
- include: boot-script.yml
- include: port-config.yml

