---
#                  _    __ _       __      _       __     ___            _        
#  _ __   ___  ___| |_ / _(_)_  __/ /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
# | '_ \ / _ \/ __| __| |_| \ \/ / || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | |_) | (_) \__ \ |_|  _| |>  <| || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
# | .__/ \___/|___/\__|_| |_/_/\_\ || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
# |_|                             \_\_|        |___/_/                            
# make-config
- name: make-config | Deploy each config file in /etc/postfix
  notify: Restart Postfix
  template:
    src:    "etc/postfix/{{ item }}.j2"
    dest:   "{{ postfix.configroot }}/{{ item }}"
    mode:   "0644"
    backup: "yes"
  with_items:
    - "main.cf"
    - "master.cf"

- name: make-config | Deploy other files in /etc/postfix
  template:
    src:    "etc/postfix/{{ item }}.j2"
    dest:   "{{ postfix.configroot }}/{{ item }}"
    mode:   "0644"
    backup: "yes"
  with_items:
    - "Makefile"

- name: make-config | Deploy aliases in /etc/postfix
  register: aliases
  template:
    src:    "etc/postfix/aliases.j2"
    dest:   "{{ postfix.configroot }}/aliases"
    mode:   "0644"
    backup: "yes"

- name: make-config | aliases.db file should be updated
  when: aliases.changed
  shell: >
    /usr/bin/newaliases
  args:
    chdir:   "{{ postfix.configroot }}"

- name: make-config | Deploy each map file in /etc/postfix
  register: mapfile
  template:
    src:    "etc/postfix/{{ item }}.j2"
    dest:   "{{ postfix.configroot }}/{{ item }}"
    mode:   "0644"
    backup: "yes"
  with_items: "{{ postfix.dbmapfiles }}"

- name: make-config | Each map file should be converted to db
  when: mapfile.changed
  shell: >
    /usr/sbin/postmap {{ item }}
  args:
    chdir:   "{{ postfix.configroot }}"
  with_items: "{{ postfix.dbmapfiles }}"

- name: make-config | Deploy credential map file in /etc/postfix
  register: credential
  template:
    src:    "etc/postfix/{{ item }}.j2"
    dest:   "{{ postfix.configroot }}/{{ item }}"
    mode:   "0600"
    owner:  "root"
    group:  "postfix"
    backup: "yes"
  with_items: "{{ postfix.credential }}"

- name: make-config | Each credential map should be converted to db
  when: credential.changed
  shell: >
    /usr/sbin/postmap {{ item }}
  args:
    chdir:   "{{ postfix.configroot }}"
  with_items: "{{ postfix.credential }}"

- name: make-config | Deploy /etc/sasl2/smtpd.conf
  template:
    src:    "etc/sasl2/smtpd.conf.j2"
    dest:   "/etc/sasl2/smtpd.conf"
    mode:   "0644"
    backup: "yes"

- name: make-config | Create dummy account into /etc/sasldb2
  register: sasldb2
  shell: >
    date | md5sum | saslpasswd2 -c -u {{ ansible_fqdn }} kijitora
  args:
    creates: "/etc/sasldb2"

- name: make-config | Disable dummy account into /etc/sasldb2
  when: sasldb2.changed
  shell: >
    saslpasswd2 -d -u {{ ansible_fqdn }} kijitora

- name: make-config | SASLv2 Password DB should be readable from Postfix
  file:
    path:  "/etc/sasldb2"
    mode:  "0640"
    owner: "root"
    group: "postfix"
    state: "file"


