---
#                  _    __ _       __      _       __     ___            _        
#  _ __   ___  ___| |_ / _(_)_  __/ /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
# | '_ \ / _ \/ __| __| |_| \ \/ / || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | |_) | (_) \__ \ |_|  _| |>  <| || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
# | .__/ \___/|___/\__|_| |_/_/\_\ || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
# |_|                             \_\_|        |___/_/                            
# port-config
- block:
    - name: port-config | SMTP(25) port should be opened
      firewalld:
        service:   "smtp"
        state:     "enabled"
        immediate: true
        permanent: true

    - name: port-config | Submission(587) port should be opened
      firewalld:
        port:      "587/tcp"
        state:     "enabled"
        immediate: true
        permanent: true
  when: ansible_os_family == "RedHat"
