---
#                  _    __ _       __      _       __     ___            _        
#  _ __   ___  ___| |_ / _(_)_  __/ /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
# | '_ \ / _ \/ __| __| |_| \ \/ / || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | |_) | (_) \__ \ |_|  _| |>  <| || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
# | .__/ \___/|___/\__|_| |_/_/\_\ || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
# |_|                             \_\_|        |___/_/                            
# rewrite-esa
- block:
  - name: rewrite-esa | RedHat | postsrsd should be installed
    yum:
      state: "present"
      name:
        - "postsrsd"

  - name: rewrite-esa | RedHat | /etc/default/postsrsd should be deployed
    notify: Restart PostSRSd
    template:
      src:   "etc/default/postsrsd-redhat.j2"
      dest:  "/etc/default/postsrsd"
      mode:  "0644"
      owner: "root"
      group: "root"
  when: ansible_os_family == "RedHat"

- block:
  - name: rewrite-esa | Debian | postsrsd should be installed
    environment:
      DEBIAN_FRONTEND: "noninteractive"
    apt:
      state: "present"
      name:
        - "postsrsd"

  - name: rewrite-esa | Debian | /etc/default/postsrsd should be deployed
    notify: Restart PostSRSd
    template:
      src:   "etc/default/postsrsd-debian.j2"
      dest:  "/etc/default/postsrsd"
      mode:  "0644"
      owner: "root"
      group: "root"
  when: ansible_os_family == "Debian"

- name: rewrite-esa | /etc/postsrsd.do-not-rewrite should be deployed
  notify: Restart PostSRSd
  template:
    src:   "etc/postsrsd.do-not-rewrite.j2"
    dest:  "/etc/postsrsd.do-not-rewrite"
    mode:  "0644"
    owner: "root"
    group: "root"

- name: rewrite-esa | PostSRSd should be started
  when: postfix.rewriteesa.started == true
  service:
    name:  "{{ postfix.rewriteesa.service }}"
    state: "started"

- name: rewrite-esa | PostSRSd should be enabled
  when: postfix.rewriteesa.enabled == true
  service:
    name:    "{{ postfix.rewriteesa.service }}"
    enabled: "yes"

