---
#                  _    __ _       __      _       __     ___            _        
#  _ __   ___  ___| |_ / _(_)_  __/ /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
# | '_ \ / _ \/ __| __| |_| \ \/ / || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | |_) | (_) \__ \ |_|  _| |>  <| || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
# | .__/ \___/|___/\__|_| |_/_/\_\ || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
# |_|                             \_\_|        |___/_/                            
# setup-table
- name: make-config | /etc/postfix/db directory should be created
  file:
    path:  "{{ postfix.backend.config }}"
    state: "directory"
    owner: "root"
    group: "postfix"
    mode:  "0750"

- name: make-config | /etc/postfix/sql directory should be created
  file:
    path:  "{{ postfix.configroot }}/sql"
    state: "directory"
    owner: "root"
    group: "postfix"
    mode:  "0750"

- name: make-config | config files for SQL should be deployed
  template:
    src:   "{{ item }}"
    dest:  "{{ postfix.backend.config }}/{{ item | basename | replace('.j2', '') }}"
    mode:  "0640"
    owner: "root"
    group: "postfix"
  with_fileglob: "templates{{ postfix.backend.config }}/*.j2"

- block:
    - name: make-config | SQL files for MySQL should be deployed
      register: sqlfiles
      template:
        src:   "{{ item }}"
        dest:  "{{ postfix.configroot }}/sql/{{ item | basename | replace('.j2', '') }}"
        mode:  "0640"
        owner: "root"
        group: "postfix"
      with_fileglob: "templates/var/lib/mysql/*.sql.j2"

    - name: setup-table | MySQL | Databases should be created
      mysql_db:
        login_user:     "{{ postfix.backend.login.username }}"
        login_password: "{{ postfix.backend.login.password }}"
        login_host:     "localhost"
        name:           "{{ postfix.backend.database }}"
        encoding:       "{{ postfix.backend.encoding }}"
        state:          "present"

    - name: setup-table | MySQL | Roles should be created
      mysql_user:
        login_user:     "{{ postfix.backend.login.username }}"
        login_password: "{{ postfix.backend.login.password }}"
        login_host:     "localhost"
        name:           "{{ postfix.backend.username }}"
        password:       "{{ postfix.backend.password }}"
        priv:           "{{ postfix.backend.grants }}"
        state:          "present"

    - name: setup-table | MySQL | Each table should be created
      when: sqlfiles.changed
      mysql_db:
        name:   "{{ postfix.backend.database }}"
        state:  "import"
        target: "{{ postfix.configroot }}/sql/email.{{ item }}.sql"
      with_items:
        - "virthosts"
        - "virtusers"
        - "vmailboxes"
        - "vmailhosts"
  when: postfix.backend.engine == "MySQL"
