---
#                  _    __ _       __      _       __     ___            _        
#  _ __   ___  ___| |_ / _(_)_  __/ /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
# | '_ \ / _ \/ __| __| |_| \ \/ / || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | |_) | (_) \__ \ |_|  _| |>  <| || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
# | .__/ \___/|___/\__|_| |_/_/\_\ || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
# |_|                             \_\_|        |___/_/                            
# smtp-milter
- block:
    - name: smtp-milter | RedHat | amavisd-new should be installed
      yum:
        name:  "{{ item }}"
        state: "present"
      with_items:
        - "amavisd-new"
        - "amavisd-milter"

    - name: smtp-milter | RedHat | spamassassin should be installed
      yum:
        name:  "{{ item }}"
        state: "present"
      with_items:
        - "spamassassin"
        - "spamass-milter"
        - "spamass-milter-postfix"

    - name: smtp-milter | RedHat | Clam should be installed
      yum:
        name:  "{{ item }}"
        state: "present"
      with_items:
        - "clamav"
        - "clamav-data"
        - "clamav-devel"
        - "clamav-lib"
        - "clamav-milter"
        - "clamav-milter-systemd"
        - "clamav-scanner-systemd"
        - "clamav-server-systemd"
        - "clamav-update"
        - "clamd"
        - "clamsmtp"
  when: ansible_os_family == "RedHat"

# -----------------------------------------------------------------------------
- block:
    - name: smtp-milter | Debian | amavisd-new should be installed
      apt:
        name:  "{{ item }}"
        state: "present"
      with_items:
        - "amavisd-new"
        - "amavisd-milter"
        - "dkimproxy"

    - name: smtp-milter | Debian | spamassassin should be installed
      apt:
        name:  "{{ item }}"
        state: "present"
      with_items:
        - "spamassassin"
        - "spamass-milter"

    - name: smtp-milter | Debian | Clam should be installed
      apt:
        name:  "{{ item }}"
        state: "present"
      with_items:
        - "clamav"
        - "clamav-base"
        - "clamav-daemon"
        - "clamav-docs"
        - "clamav-freshclam"
        - "clamav-milter"
        - "clamav-testfiles"
        - "clamdscan"
        - "clamdscan"
        - "clamsmtp"
        - "libclamav7"
        - "libclamav-dev"
  when: ansible_os_family == "Debian"
