---
#                  _    __ _       __      _       __     ___            _        
#  _ __   ___  ___| |_ / _(_)_  __/ /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
# | '_ \ / _ \/ __| __| |_| \ \/ / || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | |_) | (_) \__ \ |_|  _| |>  <| || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
# | .__/ \___/|___/\__|_| |_/_/\_\ || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
# |_|                             \_\_|        |___/_/                            
# use-openarc
- name: use-openarc | Group for OpenARC should be created
  group:
    name:  "openarc"
    state: "present"

- name: use-openarc | openarc user should be created
  user:
    createhome: "yes"
    comment:    "OpenARC Milter"
    password:   null
    name:       "openarc"
    group:      "openarc"
    groups:     "mail"
    shell:      "/sbin/nologin"
    home:       "{{ postfix.openarc.runtime }}"
    state:      "present"

- name: use-openarc | runtime directory should be 755
  file:
    path:  "{{ postfix.openarc.runtime }}"
    mode:  "0755"
    owner: "openarc"
    group: "openarc"
    state: "directory"

- name: use-openarc | /etc/arc directory should be created
  file:
    path:  "{{ postfix.openarc.confdir }}"
    mode:  "0755"
    owner: "root"
    group: "openarc"
    state: "directory"

- name: use-openarc | Sub directories in /etc/arc should be created
  file:
    path:  "{{ postfix.openarc.confdir }}/{{ item }}"
    mode:  "0750"
    owner: "openarc"
    group: "openarc"
    state: "directory"
  loop:
    - "keys"

- name: use-openarc | /etc/openarc.conf should be deployed
  notify: Restart OpenARC
  template:
    src:   "etc/openarc.conf.j2"
    dest:  "/etc/openarc.conf"
    mode:  "0644"
    owner: "root"
    group: "root"

- name: use-openarc | /etc/sysconfig/openarc should be deployed
  notify: Restart OpenARC
  template:
    src:   "etc/sysconfig/openarc.j2"
    dest:  "/etc/sysconfig/openarc"
    mode:  "0644"
    owner: "root"
    group: "root"

- name: use-openarc | tables for OpenARC should be deployed
  notify: Restart OpenARC
  template:
    src:   "etc/arc/{{ item }}.j2"
    dest:  "{{ postfix.openarc.confdir }}/{{ item }}"
    mode:  "0640"
    owner: "openarc"
    group: "openarc"
  loop:
    - "trusted-hosts"

- name: use-openarc | Each keys for OpenDKIM should be deployed to /etc/arc/keys
  notify: Restart OpenARC
  copy:
    src:   "{{ item }}"
    dest:  "{{ postfix.openarc.confdir }}/keys/{{ item | basename }}"
    mode:  "0600"
    owner: "openarc"
    group: "openarc"
  with_fileglob: "files/etc/dkim/keys/*"

- name: use-openarc | Unit file should be deployed
  register: openarc_unit_deployed
  notify: Restart OpenARC
  template:
    src:  "usr/lib/systemd/system/{{ postfix.openarc.service }}.service.j2"
    dest: "/usr/lib/systemd/system/{{ postfix.openarc.service }}.service"
    mode: "0644"

- name: use-openarc | Reload systemd
  when: openarc_unit_deployed.changed
  systemd:
    daemon_reload: "yes"
    name:  "{{ postfix.openarc.service }}"
    state: "restarted"

- name: use-openarc | OpenARC should be started
  when: postfix.openarc.started == true
  service:
    name:  "{{ postfix.openarc.service }}"
    state: "started"

- name: use-openarc | OpenARC should be enabled
  when: postfix.openarc.enabled == true
  service:
    name:    "{{ postfix.openarc.service }}"
    enabled: "yes"

