---
#                  _    __ _       __      _       __     ___            _        
#  _ __   ___  ___| |_ / _(_)_  __/ /_ __ | | ____ \ \   / / |_ __ _ ___| | _____ 
# | '_ \ / _ \/ __| __| |_| \ \/ / || '_ \| |/ / _` | | / /| __/ _` / __| |/ / __|
# | |_) | (_) \__ \ |_|  _| |>  <| || |_) |   < (_| | |/ / | || (_| \__ \   <\__ \
# | .__/ \___/|___/\__|_| |_/_/\_\ || .__/|_|\_\__, | /_/   \__\__,_|___/_|\_\___/
# |_|                             \_\_|        |___/_/                            
# use-openarc
- block:
    # There is no package for OpenARC in Debian
  - name: use-openarc | Debian | Clone OpenARC.git into /usr/local/src
    git:
      repo:   "https://github.com/trusteddomainproject/OpenARC.git"
      dest:   "/usr/local/src/{{ postfix.openarc.version }}"
      update: "no"
      version: "{{ postfix.openarc.version }}"
      accept_hostkey: "yes"

  - name: use-openarc | Debian | Developer tools should be installed
    environment:
      DEBIAN_FRONTEND: "noninteractive"
    apt:
      state: "present"
      name:  "{{ item }}"
    loop:
      - "automake"
      - "pkg-config"
      - "libtool"
      - "libglib2.0-0"
      - "libglib2.0-dev"
      - "libssl1.1"
      - "libssl-dev"
      - "libbsd-dev"

  - name: use-openarc | Debian | Compile OpenARC(1)
    register: make_openarc_aclocal
    shell: aclocal && libtoolize && autoheader && automake --add-missing && autoconf
    args:
      chdir:   "/usr/local/src/{{ postfix.openarc.version }}"
      creates: "./configure"

  - name: use-openarc | Debian | Compile OpenARC(2)
    when: make_openarc_aclocal.changed
    register: make_openarc_configure
    shell: /bin/sh ./configure
    args:
      chdir:   "/usr/local/src/{{ postfix.openarc.version }}"
      creates: "./Makefile"

  - name: use-openarc | Debian | Compile OpenARC(3)
    when: make_openarc_configure.changed
    register: make_openarc_build
    shell: LD_LIBRARY_PATH=/usr/local/lib LD_RUN_PATH=/usr/local/lib make
    args:
      chdir:   "/usr/local/src/{{ postfix.openarc.version }}"
      creates: "./libopenarc/libopenarc.la"

  - name: use-openarc | Debian | OpenARC should be installed
    when: make_openarc_build.changed
    shell: make install
    args:
      chdir:   "/usr/local/src/{{ postfix.openarc.version }}"
      creates: "/usr/local/sbin/openarc"

  - name: use-openarc | Debian | /usr/local/sbin/openarc should be linked from /usr/sbin
    file:
      src:   "/usr/local/sbin/openarc"
      dest:  "/usr/sbin/openarc"
      state: "link"
  when: ansible_os_family == "Debian"

- name: use-openarc | Group for OpenARC should be created
  group:
    name:  "openarc"
    state: "present"
  
- name: use-openarc | openarc user should be created
  user:
    createhome: "yes"
    comment:    "OpenARC Milter"
    password:   null
    name:       "openarc"
    group:      "openarc"
    groups:     "mail"
    shell:      "/sbin/nologin"
    home:       "{{ postfix.openarc.runtime }}"
    state:      "present"
  
- name: use-openarc | runtime directory should be 755
  file:
    path:  "{{ postfix.openarc.runtime }}"
    mode:  "0755"
    owner: "openarc"
    group: "openarc"
    state: "directory"
  
- name: use-openarc | /etc/arc directory should be created
  file:
    path:  "{{ postfix.openarc.confdir }}"
    mode:  "0755"
    owner: "root"
    group: "openarc"
    state: "directory"
 
- name: use-openarc | Sub directories in /etc/arc should be created
  file:
    path:  "{{ postfix.openarc.confdir }}/{{ item }}"
    mode:  "0750"
    owner: "openarc"
    group: "openarc"
    state: "directory"
  loop:
    - "keys"
  
- name: use-openarc | /etc/openarc.conf should be deployed
  notify: Restart OpenARC
  template:
    src:   "etc/openarc.conf.j2"
    dest:  "/etc/openarc.conf"
    mode:  "0644"
    owner: "root"
    group: "root"
  
- name: use-openarc | tables for OpenARC should be deployed
  notify: Restart OpenARC
  template:
    src:   "etc/arc/{{ item }}.j2"
    dest:  "{{ postfix.openarc.confdir }}/{{ item }}"
    mode:  "0640"
    owner: "openarc"
    group: "openarc"
  loop:
    - "trusted-hosts"
    - "ignored-hosts"
  
- name: use-openarc | Each keys for OpenDKIM should be deployed to /etc/arc/keys
  notify: Restart OpenARC
  copy:
    src:   "{{ item }}"
    dest:  "{{ postfix.openarc.confdir }}/keys/{{ item | basename }}"
    mode:  "0600"
    owner: "openarc"
    group: "openarc"
  with_fileglob: "files/etc/dkim/keys/*"

- block:
  - name: use-openarc | RedHat | /etc/sysconfig/openarc should be deployed
    notify: Restart OpenARC
    template:
      src:   "etc/sysconfig/openarc.j2"
      dest:  "/etc/sysconfig/openarc"
      mode:  "0644"
      owner: "root"
      group: "root"
  when: ansible_os_family == "RedHat"

- block:
  - name: use-openarc | Debian | /etc/default/openarc should be deployed
    notify: Restart OpenARC
    template:
      src:   "etc/default/openarc.j2"
      dest:  "/etc/default/openarc"
      mode:  "0644"
      owner: "root"
      group: "root"

  - name: use-openarc | Debian | /usr/local/etc/openarc.conf should be linked
    file:
      src:   "/etc/openarc.conf"
      dest:  "/usr/local/etc/openarc.conf"
      state: "link"

  - name: use-openarc | Debian | /usr/local/etc/arc should be linked
    file:
      src:   "/etc/arc"
      dest:  "/usr/local/etc/arc"
      state: "link"
  when: ansible_os_family == "Debian"

- name: use-openarc | Unit file should be deployed
  register: openarc_unit_deployed
  notify: Restart OpenARC
  template:
    src:  "usr/lib/systemd/system/{{ postfix.openarc.service }}.service.j2"
    dest: "/usr/lib/systemd/system/{{ postfix.openarc.service }}.service"
    mode: "0644"

- name: use-openarc | Reload systemd
  when: openarc_unit_deployed.changed
  systemd:
    daemon_reload: "yes"
    name:  "{{ postfix.openarc.service }}"
    state: "restarted"
  
- name: use-openarc | OpenARC should be started
  when: postfix.openarc.started == true
  service:
    name:  "{{ postfix.openarc.service }}"
    state: "started"
  
- name: use-openarc | OpenARC should be enabled
  when: postfix.openarc.enabled == true
  service:
    name:    "{{ postfix.openarc.service }}"
    enabled: "yes"

